### ISSUE TITLE
Plox check

### ISSUE THREAD

**Issue by akshaymishra7** [CalanPereira/minicompiler#1]
Hi Calan,
I found a Bug in your Code,
The .... is working

 find my resume [click here](https://codeforces.com/profile/akshaymishra409)

*Bada*
**Aur Bada**
![Screenshot (1)](https://user-images.githubusercontent.com/72158107/145859762-873eb50a-a0f6-45cc-b7cd-3d635929870d.png)

**Comment by CalanPereira** [comment]
ja na laude
